server:
  servlet:
    context-path: /
  port: 8080

spring:
  aop:
    auto: true #启动aop配置
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://118.89.155.112:3306/MysqlTest?useUnicode=true&characterEncoding=utf-8&serverTimezone=Asia/Shanghai
    username: root
    password: root
    type: com.alibaba.druid.pool.DruidDataSource

mybatis:
  type-aliases-package: com.springboot.demo.model

#pagehelper分页插件
pagehelper:
  helperDialect: mysql
  reasonable: true
  supportMethodsArguments: true
  params: count=countSql



