server:
  servlet:
    context-path: /
  port: 8080

spring:
  application:
    name: AndrewSpringBoot
  aop:
    auto: true #启动aop配置
  # 配置SBA Client连接的安全账号密码
  security:
    user:
      name: admin
      password: admin

